version: "3"

services:
  api:
    container_name: api
    build: ./backend
    command: "flask run -h 0.0.0.0"
    restart: always
    ports:
      - 8080:5000
    environment:
      - FLASK_APP=apis.app
      - FLASK_CONFIG_MODE=production
